# 0 Mathematische Einführung

## 0.1 Arrays, Matrizen und elementare Lineare Algebra

Dieses Kapitel rekapituliert die wichtigsten Elemente der Linearen Algebra, die in dieser Vorlesung gebraucht werden.
Betrachte eine Matrix $\mathbf{A}\in \mathbb{R}^{2\times 2} $

In [1]:
import numpy as np
A = np.matrix([[1, 2],[3,4]])
A

matrix([[1, 2],
        [3, 4]])

Die Matrixmultiplikation $\mathbf{A}\cdot \mathbf{A}$.

In [2]:
A*A

matrix([[ 7, 10],
        [15, 22]])

Die Multiplikation einer Matrix $\mathbf{A}\in \mathbb{R}^{n\times m}$ mit einem Vektor $\vec{b}\in \mathbb{R}^{m}$ ergibt einen Vektor $\vec{c}\in \mathbb{R}^{n}$

In [3]:
A = np.matrix([[1, 2,3,4],[5,6,7,8]])
b = np.transpose(np.matrix([1, 2,3,4]))
A*b


matrix([[30],
        [70]])

Anstelle von Matrizen (numpy.matrix) kann man auch arrays (numpy.array) verwenden. Während Matrizen immer 2-dimensionale Objekte sind, stellen array N-dimensionale Objekte dar. Es gibt hier Unterscheide bei der Multiplikation: Wir nehmen noch einmal das Beispiel von oben (diesmal als array):

In [4]:
B = np.array([[1, 2],[3,4]])
B

array([[1, 2],
       [3, 4]])

Das normale Multiplikationszeichen ergibt bei arrays die elementweise Multiplikation. Die Matrixmultiplikation

In [5]:
B*B

array([[ 1,  4],
       [ 9, 16]])

Die normale Matrixmultiplikation erhält man mittels

In [6]:
np.matmul(B,B)

array([[ 7, 10],
       [15, 22]])

In späteren Kapiteln (inbesondere bei Convolutional Neural Networks) benötigen wir auch mehrdimensionale arrays. Wir nehmen als Beispiel ein dreidimensionales array.

In [7]:
C = np.array([ [[1, 2],[3,4]],[[2, 1],[4,3]] ])
C

array([[[1, 2],
        [3, 4]],

       [[2, 1],
        [4, 3]]])

## 0.2 Mehrdimensionale Analysis

Eine skalare Funktion $f(x_1,\ldots,x_n)$ ist eine Abbildung $f:\mathbb{R}^n\rightarrow \mathbb{R}$, die einem Vektor $\vec{x}\in\mathbb{R}^n$ eine Zahl (Skalar) $f$ zuordnet.